testdbt_01:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 2
      host: dpg-co9l3pa0si5c739ef67g-a.oregon-postgres.render.com
      port: 5432
      user: testdb_xr34_user
      pass: r1vfKU7wLA1BzqtnHmyn4QU8VS7rnYnU
      dbname: testdb_xr34
      schema: testdbt_curated