version: 2

models:
  - name: clientes_ativos_por_mes
    description: "Identifica o número de clientes ativos por mês."
    columns:
      - name: mes
        description: "O mês em que os pedidos foram feitos."
        tests:
          - not_null
      - name: clientes_ativos
        description: "Número de clientes únicos que fizeram pelo menos um pedido no mês."
        tests:
          - not_null

  - name: retenção
    description: "Analisa a retenção de clientes calculando o tempo entre o primeiro e o segundo pedido."
    columns:
      - name: id_cliente
        description: "Identificador único do cliente."
        tests:
          - unique
          - not_null
      - name: data_primeiro_pedido
        description: "Data do primeiro pedido do cliente."
      - name: data_segundo_pedido
        description: "Data do segundo pedido do cliente."

  - name: cltv_analise
    description: "Calcula o Valor do Cliente ao Longo do Tempo (CLTV), incluindo gasto total, total de pedidos, e valor médio por pedido."
    tests:
      - relationships:
          to: ref('clientes')
          field: id_cliente
    columns:
      - name: id_cliente
        description: "Identificador único do cliente."
        tests:
          - unique
          - not_null
      - name: nome
        description: "Nome do cliente."
        tests:
          - not_null
      - name: data_primeira_compra
        description: "Data da primeira compra feita pelo cliente."
        tests:
          - not_null
      - name: data_ultima_compra
        description: "Data da última compra feita pelo cliente."
        tests:
          - not_null
      - name: total_pedidos
        description: "Total de pedidos feitos pelo cliente."
        tests:
          - not_null
      - name: gasto_total
        description: "Total gasto pelo cliente."
        tests:
          - not_null
      - name: valor_medio_pedido
        description: "Valor médio gasto por pedido."
        tests:
          - not_null
      - name: dias_cliente
        description: "Número de dias desde a primeira compra até a data atual."
        tests:
          - not_null

